frontend:
  deploymentName: shopverse-frontend
  replicas: 2
  image: "609898225296.dkr.ecr.us-east-1.amazonaws.com/shopverse-frontend:latest"
  serviceName: shopverse-frontend-svc
  servicePort: 80
  ingressName: shopverse-frontend-ingress
  ingressHost: "jamdarwadi.shop"

backend:
  deploymentName: shopverse-backend
  replicas: 2
  image: "609898225296.dkr.ecr.us-east-1.amazonaws.com/shopverse-backend:latest"
  serviceName: shopverse-backend-svc
  servicePort: 8080
  ingressName: shopverse-backend-ingress
  ingressHost: "api.jamdarwadi.shop"

# ──────────────────────────────────────
# MySQL
# ──────────────────────────────────────
mysql:
  database: shopverse
  user: shopverse
  rootPassword: "Admin@123"
  password: "Admin@123"
  storage: 5Gi
  storageClass: gp2
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {}

jwtSecret: "shopverse-jwt-secret"
