name: ShopVerse CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Backend Test
        working-directory: backend
        run: |
          go mod tidy
          go test ./...

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Frontend Install
        working-directory: frontend
        run: npm install

      - name: Frontend Lint
        working-directory: frontend
        run: npm run lint


  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build Images
        run: |
          docker build -t frontend:scan ./frontend
          docker build -t backend:scan ./backend

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install wget -y

          wget \
          https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.deb

          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

      - name: Scan
        run: |
          trivy image frontend:scan
          trivy image backend:scan


  build:
    runs-on: ubuntu-latest
    needs: security

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Images
        run: |
          docker build \
          -t $ECR_REGISTRY/shopverse-frontend:${GITHUB_SHA} \
          ./frontend

          docker build \
          -t $ECR_REGISTRY/shopverse-backend:${GITHUB_SHA} \
          ./backend

      - name: Push Images
        run: |
          docker push \
          $ECR_REGISTRY/shopverse-frontend:${GITHUB_SHA}

          docker push \
          $ECR_REGISTRY/shopverse-backend:${GITHUB_SHA}


  helm:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Chart
        run: |
          helm package ./helm/shopverse

      - name: Helm Login
        run: |
          aws ecr get-login-password \
          --region $AWS_REGION \
          | helm registry login \
          --username AWS \
          --password-stdin \
          $ECR_REGISTRY

      - name: Push Helm
        run: |
          helm push \
          shopverse-*.tgz \
          oci://$ECR_REGISTRY/shopverse-helmchart
