name: ShopVerse CI/CD

on:
push:
branches:
- main

env:
AWS_REGION: ${{ secrets.AWS_REGION }}
ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:

test:
name: Test
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - name: Setup Go
    uses: actions/setup-go@v5
    with:
      go-version: "1.24"

  - name: Backend Test
    working-directory: backend
    run: |
      go mod tidy
      go test ./...

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: "18"

  - name: Install Frontend
    working-directory: frontend
    run: npm install

  - name: Frontend Lint
    working-directory: frontend
    run: npm run lint
```

security:
name: Security Scan
runs-on: ubuntu-latest
needs: test

```
steps:

  - uses: actions/checkout@v4

  - name: Build Scan Images
    run: |
      docker build -t frontend:scan ./frontend
      docker build -t backend:scan ./backend

  - name: Install Trivy
    run: |
      sudo apt-get update

      sudo apt-get install -y \
        wget \
        apt-transport-https \
        gnupg \
        lsb-release

      wget -qO - \
      https://aquasecurity.github.io/trivy-repo/deb/public.key \
      | gpg --dearmor \
      | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

      echo \
      "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
      | sudo tee /etc/apt/sources.list.d/trivy.list

      sudo apt-get update

      sudo apt-get install -y trivy

  - name: Trivy Scan
    run: |
      trivy image frontend:scan
      trivy image backend:scan
```

build:
name: Build Push Update
runs-on: ubuntu-latest
needs: security

```
steps:

  - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Configure AWS
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  - name: Login ECR
    uses: aws-actions/amazon-ecr-login@v2

  - name: Build Frontend
    run: |
      docker build \
      -t $ECR_REGISTRY/shopverse-frontend:${GITHUB_SHA} \
      ./frontend

  - name: Build Backend
    run: |
      docker build \
      -t $ECR_REGISTRY/shopverse-backend:${GITHUB_SHA} \
      ./backend

  - name: Push Images
    run: |
      docker push \
      $ECR_REGISTRY/shopverse-frontend:${GITHUB_SHA}

      docker push \
      $ECR_REGISTRY/shopverse-backend:${GITHUB_SHA}


  - name: Update values.yaml
    run: |

      sed -i \
      "s|tag: .*|tag: ${GITHUB_SHA}|g" \
      helm/shopverse/values.yaml

      cat helm/shopverse/values.yaml


  - name: Commit values update
    run: |

      git config user.name "sandeshjamdar20"

      git config user.email "sandeshjamdar51@gmail.com"

      git add helm/shopverse/values.yaml

      git commit \
      -m "update image ${GITHUB_SHA}" \
      || true

      git push \
      https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
```

helm:
name: Helm Package
runs-on: ubuntu-latest
needs: build

```
steps:

  - uses: actions/checkout@v4

  - name: Install Helm
    uses: azure/setup-helm@v3

  - name: Package Chart
    run: |
      helm package ./helm/shopverse

  - name: Login Helm
    run: |
      aws ecr get-login-password \
      --region $AWS_REGION \
      | helm registry login \
      --username AWS \
      --password-stdin \
      $ECR_REGISTRY

  - name: Push Chart
    run: |
      helm push \
      shopverse-*.tgz \
      oci://$ECR_REGISTRY/shopverse-helmchart
```
