name: ShopVerse CI/CD

on:
push:
branches:
- main

env:
AWS_REGION: ${{ secrets.AWS_REGION }}
ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
HELM_CHART_NAME: shopverse
TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:

test:
name: Test
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: "1.24"

  - name: Update go.sum
    working-directory: ./backend
    run: go mod tidy

  - name: Run Go tests
    working-directory: ./backend
    run: go test ./...

  - name: Set up Node.js
    uses: actions/setup-node@v4
    with:
      node-version: "18"

  - name: Install frontend dependencies
    working-directory: ./frontend
    run: npm install

  - name: Run frontend lint
    working-directory: ./frontend
    run: |
      npx eslint . \
      --ext js,jsx \
      --report-unused-disable-directives \
      --max-warnings 0 \
      --config .eslintrc.cjs
```

security-scan:
name: Security Scan
runs-on: ubuntu-latest
needs: test

```
steps:
  - uses: actions/checkout@v4

  - name: Build frontend image
    run: docker build -t shopverse-frontend:scan ./frontend

  - name: Build backend image
    run: docker build -t shopverse-backend:scan ./backend

  - name: Install Trivy
    run: |
      sudo apt-get update

      sudo apt-get install -y \
        wget \
        apt-transport-https \
        gnupg

      wget -qO - \
      https://aquasecurity.github.io/trivy-repo/deb/public.key \
      | gpg --dearmor \
      | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

      echo \
      "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
      | sudo tee /etc/apt/sources.list.d/trivy.list

      sudo apt-get update

      sudo apt-get install -y trivy

  - name: Run Trivy frontend
    run: |
      trivy image \
      --exit-code 1 \
      --severity CRITICAL \
      shopverse-frontend:scan

  - name: Run Trivy backend
    run: |
      trivy image \
      --exit-code 1 \
      --severity CRITICAL \
      shopverse-backend:scan
```

build-and-push:
name: Build Push Helm
runs-on: ubuntu-latest
needs: security-scan

```
steps:

  - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Configure AWS
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  - name: Login ECR
    uses: aws-actions/amazon-ecr-login@v2

  - name: Ensure repositories
    run: |
      for repo in \
        shopverse-frontend \
        shopverse-backend \
        shopverse-helmchart
      do
        aws ecr describe-repositories \
        --repository-names $repo \
        || \
        aws ecr create-repository \
        --repository-name $repo
      done

  - name: Build frontend
    run: |
      docker build \
      -t $ECR_REGISTRY/shopverse-frontend:${GITHUB_SHA} \
      ./frontend

  - name: Build backend
    run: |
      docker build \
      -t $ECR_REGISTRY/shopverse-backend:${GITHUB_SHA} \
      ./backend

  - name: Push images
    run: |
      docker push \
      $ECR_REGISTRY/shopverse-frontend:${GITHUB_SHA}

      docker push \
      $ECR_REGISTRY/shopverse-backend:${GITHUB_SHA}

  - name: Update values.yaml
    run: |
      sed -i \
      "s|tag:.*|tag: ${GITHUB_SHA}|g" \
      helm/shopverse/values.yaml

      cat helm/shopverse/values.yaml

  - name: Push updated values.yaml
    run: |
      git config --global user.name "sandeshjamdar20"

      git config --global user.email "sandeshjamdar51@gmail.com"

      git add helm/shopverse/values.yaml

      git commit \
      -m "update image ${GITHUB_SHA}" \
      || echo "No changes"

      git push

  - name: Install Helm
    uses: azure/setup-helm@v3

  - name: Helm Login
    run: |
      aws ecr get-login-password \
      --region $AWS_REGION \
      | helm registry login \
      --username AWS \
      --password-stdin \
      $ECR_REGISTRY

  - name: Package Helm
    run: |
      helm package \
      ./helm/shopverse \
      --version 1.0.0-${GITHUB_SHA}

  - name: Push Helm
    run: |
      helm push \
      shopverse-1.0.0-${GITHUB_SHA}.tgz \
      oci://$ECR_REGISTRY/shopverse-helmchart
